#####
##### GENERATED BY testing/utils/host-to-host.sh
#####   do not modify
#####

east# ../../guestbin/prep.sh
east# ipsec start
east# ../../guestbin/wait-until-pluto-started
east# ipsec add westnet-eastnet
east# echo "initdone"

west# ../../guestbin/prep.sh
west# ipsec start
west# ../../guestbin/wait-until-pluto-started
west# ipsec add westnet-eastnet
west# echo "initdone"

west# ipsec up westnet-eastnet # sanitize-retransmits
west# ipsec _kernel state
west# ipsec _kernel policy
east# ../../guestbin/ping-once.sh --up 192.1.2.45 # west
west# ../../guestbin/ping-once.sh --up 192.1.2.23 # east
rise# ../../guestbin/ping-once.sh --up 192.0.1.15 # set
set# ../../guestbin/ping-once.sh --up 192.0.2.12 # rise

west# ipsec down westnet-eastnet
west# ipsec _kernel state
west# ipsec _kernel policy
