connections {
	road-eastnet-ikev2 {
		fragmentation=yes
		version=2
		local_addrs=192.1.2.23
		remote_addrs=%any
		children {
			road-eastnet-ikev2 {
				start_action=none
				remote_ts=192.1.3.209/32
				local_ts=192.0.2.0/24
			}
			
		}
		local-0 {
			auth = psk
			id = @east
		}
		remote-0 {
			auth = psk
			id = @road
		}
	}
}
pools {
}
authorities {
}
secrets {
	ike-@road@east {
		secret = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
		id-0=@road
		id-1=@east
	}
}
