# /etc/ipsec.conf - Libreswan IPsec configuration file

config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	dumpdir=/tmp
	plutodebug=all
	autoall-sweep=no

conn alpha
	left=1.2.3.4
	right=5.6.7.8
	auto=add
