# /etc/ipsec.conf - Libreswan IPsec configuration file

config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	dumpdir=/tmp
	plutodebug=all
	autoall-sweep=no

conn alpha
	left=1.2.3.4
	right=5.6.7.8
	auto=add

conn beta
	left=2.3.4.5
	right=6.7.8.9
	auto=add

conn gamma
	left=3.4.5.6
	right=7.8.9.10
	auto=add

conn delta
	left=4.5.6.7
	leftsubnets=10.0.0.0/24
	right=8.9.10.11
	rightsubnets=192.168.0.0/24,192.168.1.0/24
	auto=add
