# /etc/ipsec.conf - Strongswan IPsec configuration file

conn westnet-eastnet-ikev2
	authby=rsasig
	leftauth=ike:rsa/pss-sha256-sha384-sha512
	rightauth=ike:rsa/pss-sha256-sha384-sha512
	#auto=start
	left=192.1.2.45
	leftsubnet=192.0.1.0/24
	leftcert=/etc/strongswan/swanctl/x509/west.crt
	leftsendcert=never
	leftid="C=CA, ST=Ontario, L=Toronto, O=Libreswan, OU=Test Department, CN=west.testing.libreswan.org, E=user-west@testing.libreswan.org"
	right=192.1.2.23
	rightsubnet=192.0.2.0/24
	rightcert=/etc/strongswan/swanctl/x509/east.crt
	rightsendcert=never
	rightid="C=CA, ST=Ontario, L=Toronto, O=Libreswan, OU=Test Department, CN=east.testing.libreswan.org, E=user-east@testing.libreswan.org"
	# strongswan options
	keyexchange=ikev2
	auto=add
	fragmentation=yes

