#####
##### GENERATED BY testing/utils/host-to-host.sh
#####   do not modify

east# /testing/guestbin/swan-prep --46
east# ipsec start
east# ../../guestbin/wait-until-pluto-started
east# ipsec whack --impair suppress_retransmits
east# ipsec add west-east
east# echo "initdone"

west# /testing/guestbin/swan-prep --46
west# ipsec start
west# ../../guestbin/wait-until-pluto-started
west# ipsec add west-east
west# echo "initdone"

west# ipsec up west-east
west# ipsec _kernel state
west# ipsec _kernel policy
west# ../../guestbin/ping-once.sh --up 2001:db8:1:2::23
west# ipsec down west-east
west# ipsec _kernel state
