conn clear
	type=passthrough
	authby=never
	left=%defaultroute
	right=%group
	auto=ondemand

# peers that use a certificate on both ends
conn oe-base-cert
	type=tunnel
	narrowing=yes
	left=%defaultroute
	leftmodecfgclient=yes
	leftcat=yes
	rightauth=rsasig
	rightrsasigkey=%cert
	rightid=%fromcert
	right=%opportunisticgroup
	rightaddresspool=10.0.10.1-10.0.10.200

# peer using authnull, CAT: it is given an address from the pool
conn oe-base-asymmetric
	type=tunnel
	narrowing=yes
	left=%defaultroute
	leftmodecfgclient=yes
	leftcat=yes
	rightid=%null
	rightauth=null
	right=%opportunisticgroup
	rightaddresspool=10.0.10.1-10.0.10.200

conn clear-or-private
	also=oe-base-asymmetric
	failureshunt=passthrough
	negotiationshunt=passthrough
	auto=add

conn private-or-clear
	also=oe-base-cert
	failureshunt=passthrough
	negotiationshunt=passthrough
	auto=ondemand

conn private
	also=oe-base-cert
	failureshunt=drop
	negotiationshunt=drop
	auto=ondemand

conn block
	type=drop
	authby=never
	left=%defaultroute
	right=%group
	auto=ondemand
