#####
##### GENERATED BY testing/utils/host-to-host.sh
#####   do not modify

east# ../../guestbin/prep.sh
east# ipsec start
east# ../../guestbin/wait-until-pluto-started
east# ipsec whack --impair suppress_retransmits
east# ipsec add west-east
east# echo "initdone"

west# ../../guestbin/prep.sh
west# ipsec start
west# ../../guestbin/wait-until-pluto-started
west# ipsec whack --impair suppress_retransmits
west# ipsec add west-east
west# echo "initdone"

west# ipsec route west-east
west# ipsec _kernel state
west# ipsec _kernel policy

# trigger acquire using UDP
west# echo 'TRIGGER' | nc -u -w 1 192.1.2.23 7
west# ../../guestbin/wait-for-pluto.sh '^".*#2: initiator established Child SA'
west# ../../guestbin/ping-once.sh --up 192.1.2.23

# wait for larval state to clear; hack
west# ../../guestbin/wait-for.sh --no-match 'spi 0x00000000' ipsec _kernel state
west# ipsec _kernel state
west# ipsec _kernel policy
west# ipsec down west-east
west# ipsec _kernel state
