# /usr/local/strongswan/etc/ipsec.conf - Strongswan IPsec configuration file

conn westnet-eastnet-ikev2
	# DANGER left<->right
	left=192.1.2.45
	leftid="C=CH, O=strongSwan, CN=strongWest"
	leftcert=/etc/strongswan/ipsec.d/certs/west.crt
	leftsubnet=192.0.1.0/24
	leftsendcert=always
	right=192.1.2.23
	rightid="C=CH, O=strongSwan, CN=strongEast"
	rightsubnet=192.0.2.0/24
	auto=add
	fragmentation=yes
