connections {
	client {
		proposals=aes256-sha2_512-modp2048, default
		version=2
		vips=0.0.0.0
		remote_addrs=192.1.2.23
		children {
			client {
				start_action=none
				remote_ts=192.0.2.0/24
			}
			
		}
		local-0 {
			auth = psk
		}
		remote-0 {
			auth = psk
		}
	}
}
pools {
}
authorities {
}
secrets {
	ike- {
		secret = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
	}
}
