connections {
	westnet-eastnet-ikev2 {
		#obsoleted option leftnexthop=192.1.2.23
		#=Right
		#obsoleted option rightnexthop=192.1.2.45
		fragmentation=yes
		proposals=aes128-sha1-modp2048, default
		version=2
		local_addrs=192.1.2.45
		remote_addrs=192.1.2.23
		children {
			westnet-eastnet-ikev2 {
				start_action=none
				esp_proposals=aes128-sha1-modp2048, default
				mode=tunnel
			}
			
		}
		local-0 {
			auth = psk
			id = @west
		}
		remote-0 {
			auth = psk
			id = @east
		}
	}
}
pools {
}
authorities {
}
secrets {
	ike-@west@east {
		secret = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
		id-0=@west
		id-1=@east
	}
}
