connections {
    west {
	local_addrs = 2001:db8:1:2::45
	remote_addrs = 2001:db8:1:2::23
	mobike = no
	version = 2
	proposals = aes-sha2_256-modp2048
	vips = ::
	local {
	    auth = psk
	    id = @west
	}
	remote {
	    auth = psk
	    id = @east
	}
	children {
	    rw-eastnet-ipv6 {
		remote_ts = ::0/0
		esp_proposals = aes128-sha2_512
	    }
	}
    }
}
