connections {
	westnet-eastnet-ikev2 {
		#auto=start
		#=strongswan
		fragmentation=yes
		version=2
		local_addrs=192.1.2.23
		send_cert=never
		remote_addrs=192.1.2.45
		#leftsend_cert=never
		children {
			westnet-eastnet-ikev2 {
				start_action=none
				local_ts=192.0.2.0/24
				remote_ts=192.0.1.0/24
			}
			
		}
		local-0 {
			auth = ike:rsa/pss-sha384
			certs = /etc/strongswan/swanctl/x509/east.crt
			id = "C=CA, ST=Ontario, L=Toronto, O=Libreswan, OU=Test Department, CN=east.testing.libreswan.org, E=user-east@testing.libreswan.org"
		}
		remote-0 {
			auth = ike:rsa/pss-sha384
			certs = /etc/strongswan/swanctl/x509/west.crt
			id = "C=CA, ST=Ontario, L=Toronto, O=Libreswan, OU=Test Department, CN=west.testing.libreswan.org, E=user-west@testing.libreswan.org"
		}
	}
}
pools {
}
authorities {
}
secrets {
	rsa- {
		file=/etc/strongswan/swanctl/rsa/east.key
		secret="foobar"
	}
}
