#!/bin/sh

if test "$#" -eq 0 ; then
    cat <<EOF 1>&2
Usage:
  $0 <documentation.xml> <additional-files>
Update AUTHORS list in <documentation.xml> based on git logs.
<additional-files> is anything pulled in by the documentation file.
EOF
   exit 1
fi

xml=$1 ; shift
echo $xml 1>&2

(
    sed -n -e '0,/<title>AUTHOR<\/title>/p' $xml

    cat <<EOF
    <!-- generated by: ./mk/authors.sh $xml $@ -->
    <simplelist type='inline'>
EOF

    {
	find $xml "$@" -type f -print
    } | {
	while read f ; do
	    git log --follow --format='%an' $f
	done
    } | {
	# transform name to something entity friendly
	sed -e 's,[ ],,g' \
	    -e 's/^vukasink$/VukasinKaradzic/' \
	    -e 's/^Vukasin$/VukasinKaradzic/' \
	    -e 's/^AntonyandPaul$/AntonyAntony\nPaulWouters/' \
	    -e 's/^Rishabh04-02$/Rishabh/' \
	    -e '/systemcrash/d' \
	    -e '/root/d'
     } | {
	sort -u
     } | {
	sed -e 's,\(.*\),      <member><author>\&\1;</author></member>,'
    }

    cat <<EOF
    </simplelist>
  </refsect1>
</refentry>
EOF
) > $xml.tmp

mv $xml.tmp $xml
git diff HEAD -- $xml | cat
