connections {
	rw-eap {
		fragmentation=yes
		dpd_delay=300s
		proposals=aes256gcm16-sha256-modp3072,aes256-sha256-modp3072,aes256gcm16-sha512-modp4096,aes256-sha256-modp1024,aes256-sha1-modp1024
		version=2
		local_addrs=192.1.2.23
		reauth_time=0s
		remote_addrs=%any
		pools=pool-subnet-100-64-10-0/24
		#rightsend_cert=never
		children {
			rw-eap {
				start_action=none
				esp_proposals=aes256gcm16-sha256-modp3072,aes256-sha256-modp3072,aes256gcm16-sha512-modp4096,aes256-sha256-modp1024,aes256-sha1
				local_ts=0.0.0.0/0
				dpd_action=clear
			}
		}
		local-0 {
			auth = pubkey
			certs = /etc/strongswan/swanctl/x509/east.crt
			id = @east.testing.libreswan.org
		}
		remote-0 {
			auth = eap-tls
			eap_id=%any
			aaa_id=east.testing.libreswan.org
		}
	}
}
pools {
	pool-subnet-100-64-10-0/24 {
		addrs=100.64.10.0/24
	}
}
authorities {
}
secrets {
	rsa- {
		file="/etc/strongswan/swanctl/rsa/east.key"
	}
}
