connections {
	rw-eap {
		version=2
		local_addrs=192.1.3.209
		vips=0.0.0.0
		remote_addrs=192.1.2.23
		children {
			rw-eap {
				start_action=none
				remote_ts=192.0.2.0/24
			}
			
		}
		local-0 {
			auth = eap
			certs = /etc/strongswan/swanctl/x509/road.crt
		}
		remote-0 {
			auth = pubkey
			id = @east.testing.libreswan.org
		}
	}
}
pools {
}
authorities {
}
secrets {
	rsa- {
		file="/etc/strongswan/swanctl/rsa/road.key"
	}
}
