config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	plutodebug=all,crypt
	dumpdir=/tmp

conn %default
	leftsourceip=192.0.1.254
	leftsubnet=192.0.1.0/24
	rightsourceip=192.0.2.254
	rightsubnet=192.0.2.0/24
        left=192.1.2.45
        leftid=%fromcert
        leftrsasigkey=%cert
        right=192.1.2.23
        rightid=%fromcert
        rightrsasigkey=%cert

conn east
	rightcert=east
	ike=aes_gcm;modp2048;addke1=ml_kem_768+ecp521

conn west-mlkem
	leftcert=west
	ike=aes_gcm;modp2048;addke1=ml_kem_768

conn west-ecp
	leftcert=west
	ike=aes_gcm;modp2048;addke1=ecp521
