connections {
	roadnet-eastnet-ikev2 {
		version=2
		local_addrs=192.1.2.23
		mobike=yes
		remote_addrs=%any
		pools=pool-subnet-192-0-3-0/24
		children {
			roadnet-eastnet-ikev2 {
				start_action=none
				esp_proposals=aes256-sha2_512, default
				local_ts=192.0.2.0/24
			}
			
		}
		local-0 {
			auth = psk
			id = @east
		}
		remote-0 {
			auth = psk
			id = %any
		}
	}
}
pools {
	pool-subnet-192-0-3-0/24 {
		addrs=198.18.66.0/24
	}
}
authorities {
}
secrets {
	ike-@east@road {
		secret = "ABCDEFGHIJ12345678910"
		id-0=@east
		id-1=@road
	}
}
