# /etc/ipsec.conf - Libreswan IPsec configuration file

version 2.0

config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	dumpdir=/tmp

conn v6-tunnel
	keyexchange=ikev2
	also=west-east-base-ipv6
	also=west-east-base-id-nss
	type=iptfs

include	/testing/baseconfigs/all/etc/ipsec.d/ipsec.conf.common
