'\" t
.\"     Title: IPSEC_RSASIGKEY
.\"    Author: Paul Wouters
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/06/2013
.\"    Manual: Executable programs
.\"    Source: libreswan
.\"  Language: English
.\"
.TH "IPSEC_RSASIGKEY" "8" "09/06/2013" "libreswan" "Executable programs"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipsec_rsasigkey \- generate RSA signature key
.SH "SYNOPSIS"
.HP \w'\fBipsec\fR\ 'u
\fBipsec\fR \fIrsasigkey\fR [\-\-verbose] [\-\-random\ \fIfilename\fR] [\-\-configdir\ \fInssdbdir\fR] [\-\-password\ \fInsspassword\fR] [\-\-hostname\ \fIhostname\fR] [nbits]
.HP \w'\fBipsec\fR\ 'u
\fBipsec\fR \fIrsasigkey\fR [\-\-verbose] [\-\-configdir\ \fInssdbdir\fR] [\-\-password\ \fInsspassword\fR] [\-\-hostname\ \fIhostname\fR]
.SH "DESCRIPTION"
.PP
\fIRsasigkey\fR
generates an RSA public/private key pair, suitable for digital signatures, of (exactly)
\fInbits\fR
bits (that is, two primes each of exactly
\fInbits\fR/2 bits, and related numbers) and emits it on standard output as ASCII (mostly hex) data\&.
\fInbits\fR
must be a multiple of 16\&.
.PP
The public exponent is forced to the value
\fB3\fR, which has important speed advantages for signature checking\&. Beware that the resulting keys have known weaknesses as encryption keys
\fBand should not be used for that purpose\fR\&.
.PP
The
\fB\-\-verbose\fR
option makes\fIrsasigkey\fR
give a running commentary on standard error\&. By default, it works in silence until it is ready to generate output\&.
.PP
The
\fB\-\-random\fR
option specifies a source for random bits used to seed the crypto library\*(Aqs RNG\&. The default is
/dev/random
(see
\fBrandom\fR(4))\&. FreeS/WAN and Openswan without NSS support used this option to specify the random source used to directly create keys\&. Libreswan only uses it to seed the crypto libraries RNG\&. Under Linux with hardware random support, special devices might show up as
/dev/*rng*
devices\&. However, these should never be access directly using this option, as hardware failures could lead to extremely non\-random values (streams of zeroes have been observed in the wild)
.PP
The
\fB\-\-configdir\fR
option specifies the nss configuration directory to use\&. This is the directory where the NSS certificate, key and security modules databases reside\&. The default value is
/etc/ipsec\&.d\&.
.PP
The
\fB\-\-password\fR
option specifies the nss cryptographic module authentication password if the NSS module has been configured to require it\&. A password is required by hardware tokens and also by the internal softotken module when configured to run in FIPS mode\&.
.PP
The
\fB\-\-hostname\fR
option specifies what host name to use in the first line of the output (see below); the default is what
\fBgethostname\fR(2)
returns\&.
.PP
The output format looks like this (with long numbers trimmed down for clarity):
.sp
.if n \{\
.RS 4
.\}
.nf

	# RSA 2048 bits   xy\&.example\&.com   Sat Apr 15 13:53:22 2000
	# for signatures only, UNSAFE FOR ENCRYPTION
	#pubkey=0sAQOF8tZ2NZt\&.\&.\&.Y1P+buFuFn/
	Modulus: 0xcc2a86fcf440\&.\&.\&.cf1011abb82d1
	PublicExponent: 0x03
	# everything after this point is secret
	PrivateExponent: 0x881c59fdf8\&.\&.\&.ab05c8c77d23
	Prime1: 0xf49fd1f779\&.\&.\&.46504c7bf3
	Prime2: 0xd5a9108453\&.\&.\&.321d43cb2b
	Exponent1: 0xa31536a4fb\&.\&.\&.536d98adda7f7
	Exponent2: 0x8e70b5ad8d\&.\&.\&.9142168d7dcc7
	Coefficient: 0xafb761d001\&.\&.\&.0c13e98d98

.fi
.if n \{\
.RE
.\}
.sp
The first (comment) line, indicating the nature and date of the key, and giving a host name, is used by
\fBipsec_showhostkey\fR(8)
when generating some forms of key output\&.
.PP
The commented\-out
\fBpubkey=\fR
line contains the public key, the public exponent and the modulus combined in approximately RFC 2537 format (the one deviation is that the combined value is given with a
\fI0s\fR
prefix, rather than in unadorned base\-64), suitable for use in the
ipsec\&.conf
file\&.
.PP
The
\fBModulus\fR,
\fBPublicExponent\fR
and
\fBPrivateExponent\fR
lines give the basic signing and verification data\&.
.PP
The
\fBPrime1\fR
and
\fBPrime2\fR
lines give the primes themselves (aka
\fIp\fR
and
\fIq\fR), largest first\&. The
\fBExponent1\fR
and
\fBExponent2\fR
lines give the private exponent mod
\fIp\-1\fR
and
\fIq\-1\fR
respectively\&. The
\fBCoefficient\fR
line gives the Chinese Remainder Theorem coefficient, which is the inverse of
\fIq\fR, mod
\fIp\fR\&. These additional numbers (which must all be kept as secret as the private exponent) are precomputed aids to rapid signature generation\&. When NSS is used, these values are not available outside the NSS security database (softtoken or hardware token) and are instead filled in with the CKA_ID\&.
.PP
No attempt is made to break long lines\&.
.PP
The US patent on the RSA algorithm expired 20 Sept 2000\&.
.SH "EXAMPLES"
.PP
\fBipsec rsasigkey \-\-verbose 4096 >mykey\&.txt\fR
.RS 4
generates a 4096\-bit signature key and puts it in the file
mykey\&.txt, with running commentary on standard error\&. The file contents can be inserted verbatim into a suitable entry in the
ipsec\&.secrets
file (see
\fBipsec_secrets\fR(5)), and the public key can then be extracted and edited into the
ipsec\&.conf
(see
\fBipsec_showhostkey\fR(8))\&.
.RE
.SH "FILES"
.PP
/dev/random, /dev/urandom
.SH "SEE ALSO"
.PP
\fBrandom\fR(4),
\fBrngd\fR(8),
\fBipsec_showhostkey\fR(8),
\fIApplied Cryptography, 2nd\&. ed\&., by Bruce Schneier, Wiley 1996\fR,
\fIRFCs 2537, 2313\fR,
\fIGNU MP, the GNU multiple precision arithmetic library, edition 2\&.0\&.2, by Torbj Granlund\fR
.SH "HISTORY"
.PP
Originally written for the Linux FreeS/WAN project <\m[blue]\fBhttp://www\&.freeswan\&.org\fR\m[]> by Henry Spencer\&. Updated for the Libreswan Project by Paul Wouters\&.
.PP
The
\fI\-\-round\fR
and
\fI\-\-noopt\fR
options were obsoleted as these were only used with the old non\-library crypto code
.PP
The
\fI\-\-random\fR
device is only used for seeding the crypto library, not for direct random to generate keys
.SH "BUGS"
.PP
There is an internal limit on
\fInbits\fR, currently 20000\&.
.PP
\fIrsasigkey\fR\*(Aqs run time is difficult to predict, since
/dev/random
output can be arbitrarily delayed if the system\*(Aqs entropy pool is low on randomness, and the time taken by the search for primes is also somewhat unpredictable\&. Specifically, embedded systems and most virtual machines are low on entropy\&. In such a situation, consider generating the RSA key on another machine, and copying
ipsec\&.secrets
and the
ipsec\&.d/*db
files to the embedded platform\&. Note that NSS embeds the full path in the DB files, so the path on proxy machine must be identical to the path on the destination machine\&.
.SH "AUTHOR"
.PP
\fBPaul Wouters\fR
.RS 4
placeholder to suppress warning
.RE
