
ifdef obj
my_inc_base = $(obj)
else
my_inc_base = .
O_TARGET := ixp4xx.o
endif

obj-$(CONFIG_OCF_IXP4XX)     += $(obj-base)ixp4xx.o

EXTRA_CFLAGS += -I$(my_inc_base)/.


ifdef obj
my_inc_base = $(obj)
else
my_inc_base = .
O_TARGET := ixp4xx.o
endif

obj-$(CONFIG_OCF_IXP4XX)     += $(obj-base)ixp4xx.o

EXTRA_CFLAGS += -I$(my_inc_base)/.

