# /etc/ipsec.conf - Libreswan IPsec configuration file

config setup
	plutodebug="all"
	logtime=no
	logappend=no
	logfile=/tmp/pluto.log
	dumpdir=/tmp

conn westnet-eastnet-ikev2
	left=192.1.2.45
	leftsubnet=192.0.1.0/24
	authby=rsasig,secret
	right=192.1.2.23
	rightauth=secret
	send-supported-auth-methods=yes
