connections {
	westnet-eastnet-ikev2 {
		#leftcert=/etc/strongswan/swanctl/x509/west.crt
		#leftsendcert=never
		#leftid="C=CA, ST=Ontario, O=Libreswan, OU=Test Department, CN=west.testing.libreswan.org, E=testing.libreswan.org"
		#=strongswan
		fragmentation=yes
		version=2
		local_addrs=192.1.2.23
		send_cert=always
		remote_addrs=%any
		children {
			westnet-eastnet-ikev2 {
				start_action=none
				local_ts=192.0.2.0/24
				remote_ts=192.0.1.0/24
			}
			
		}
		local-0 {
			auth = ike:rsa/pss-sha256
			certs = /etc/strongswan/swanctl/x509/east.crt
			id = "C=CA/ST=Ontario/O=Libreswan/OU=Test Department/CN=east.testing.libreswan.org/E=testing.libreswan.org"
		}
		remote-0 {
			auth = ike:rsa/pss-sha256
		}
	}
}
pools {
}
authorities {
}
secrets {
	rsa- {
		file=/etc/strongswan/swanctl/rsa/east.key
		secret="foobar"
	}
}
