'\" t
.\"     Title: _IMPORT_CRL
.\"    Author: Matt Rogers
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 03/15/2015
.\"    Manual: Executable programs
.\"    Source: libreswan
.\"  Language: English
.\"
.TH "_IMPORT_CRL" "8" "03/15/2015" "libreswan" "Executable programs"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
_import_crl \- helper program for importing a crl to the NSS database
.SH "DESCRIPTION"
.PP
\fI_import_crl\fR
is spawned by
\fBpluto\fR
in order to add or update a CRL in the NSS database (default: /etc/ipsec\&.d)
.SH "SEE ALSO"
.PP
\fBpluto\fR(8)\&.
.SH "HISTORY"
.PP
Man page written for the Libreswan project <\m[blue]\fBhttp://www\&.libreswan\&.org/\fR\m[]> by Matt Rogers
.SH "AUTHOR"
.PP
\fBMatt Rogers\fR
.RS 4
placeholder to suppress warning
.RE
