# /etc/ipsec.conf - Libreswan IPsec configuration file

config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	dumpdir=/tmp
	plutodebug=all
	autoall-reconcile=yes

conn alpha
	left=1.2.3.4
	right=5.6.7.8
	auto=add

conn viaiface
	left=%dummy0
	right=5.6.7.9
	auto=add
