config setup
	# put the logs in /tmp for the UMLs, so that we can operate
	# without syslogd, which seems to break on UMLs
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	dumpdir=/tmp
	plutodebug=all

conn eastnet
	right=192.1.2.23
	authby=secret
	rightid=@east
	rightmodecfgserver=yes
	leftmodecfgclient=yes
	rightsubnet=192.0.2.0/24

conn any-eastnet
	also=eastnet
	left=%any
	leftaddresspool=100.64.13.2-100.64.13.254
	leftid=@GroupID
	modecfgdns="1.2.3.4, 5.6.7.8"
	modecfgdomains="libreswan.org"

conn west-eastnet
	also=eastnet
	narrowing=yes
	left=%defaultroute
	leftid=@GroupID
	ignore-peer-dns=yes
	leftsubnet=0.0.0.0/0
