# /etc/ipsec.conf - Libreswan IPsec configuration file

config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	plutodebug="all"
	dumpdir=/tmp
	ikev1-policy=accept

conn %default
	left=192.1.2.45
	right=1.1.1.1
	keyexchange=ikev2
