connections {
	roadnet-eastnet-ikev2 {
		#=Right
		version=2
		local_addrs=192.1.2.23
		mobike=no
		remote_addrs=%any
		pools=pool-subnet-192-0-2-0/24
		children {
			roadnet-eastnet-ikev2 {
				start_action=none
				esp_proposals=aes128-sha2_512
				local_ts=0.0.0.0/0
			}
			
		}
		local-0 {
			auth = psk
			id = @east
		}
		remote-0 {
			auth = psk
			id = %any
		}
	}
}
pools {
	pool-subnet-192-0-2-0/24 {
		addrs=192.0.2.0/24
	}
}
authorities {
}
secrets {
	ike-@east@road {
		secret = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
		id-0=@east
		id-1=@road
	}
}
