config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	plutodebug=all
	dumpdir=/tmp

conn west-east
	left=192.1.2.45
	leftid="@west"
	right=192.1.2.23
	rightid="@east"
	authby=secret
	type=transport
	compress=no
	phase2=esp
