conn clear
	type=passthrough
	authby=never
	left=%defaultroute
	right=%group
	auto=route

conn oe-base-match-id
	left=%defaultroute
	leftauth=rsasig
	leftmodecfgclient=yes
	leftcat=yes
	right=%opportunisticgroup
	rightid=%any
	rightrsasigkey=%dnsondemand
	rightauth=rsasig
	rightaddresspool=10.0.10.1-10.0.10.200
	dns-match-id=yes
	narrowing=yes

conn clear-or-private
	also=oe-base-match-id
	failureshunt=passthrough
	negotiationshunt=passthrough
	auto=add

conn private-or-clear
	also=oe-base-match-id
	failureshunt=passthrough
	negotiationshunt=passthrough
	auto=route

conn private
	also=oe-base-match-id
	failureshunt=drop
	negotiationshunt=drop
	auto=route

conn block
	type=drop
	authby=never
	left=%defaultroute
	right=%group
	auto=route
