# /usr/local/strongswan/etc/ipsec.conf - Strongswan IPsec configuration file

conn westnet-eastnet-ikev2
	# DANGER left<->right
	left=192.1.2.23
	leftid="C=CH, O=strongSwan, CN=strongEast"
	leftcert=/etc/strongswan/ipsec.d/certs/east.crt
	leftsubnet=192.0.2.0/24
	leftsendcert=always
	right=192.1.2.45
	rightid="C=CH, O=strongSwan, CN=strongWest"
	rightsubnet=192.0.1.0/24
	auto=add
	fragmentation=yes
