
KLIPSSRC=${LIBRESWANSRCDIR}/linux/net/ipsec

MODULE_DEF_INCLUDE=${LIBRESWANSRCDIR}/packaging/linus/config-all.h
MODULE_DEFCONFIG?=${KLIPSSRC}/defconfig
MOD24BUILDDIR?=${LIBRESWANSRCDIR}/modobj24
MODBUILDDIR?=${LIBRESWANSRCDIR}/modobj

MODULE_FLAGS:=KLIPSMODULE=true -f ${MODULE_DEFCONFIG}

PORTINCLUDE+=-I${LIBRESWANSRCDIR}/ports/linux/include
PORTDEFINE=-DKLIPS -DSCANDIR_HAS_CONST

# include KLIPS support
USE_KLIPS?=true

# build modules, etc. for KLIPS.
BUILD_KLIPS?=true
