# New files should have dropped in, and we are ready to restart
ipsec restart
../../guestbin/wait-until-pluto-started
ipsec connectionstatus 192.1.2.45-to-192.1.2.23
# connection is ondemand, but we will --up so we can see X.509 auth
# name is generated by System Role
ipsec up 192.1.2.45-to-192.1.2.23 # sanitize-retransmits
../../guestbin/ping-once.sh --up -I 192.1.2.45 192.1.2.23
# show non-zero IPsec traffic counters
ipsec trafficstatus
echo done
