#####
##### GENERATED BY testing/utils/host-to-host.sh
#####   do not modify
#####

east# /testing/guestbin/swan-prep
east# ipsec start
east# ../../guestbin/wait-until-pluto-started
east# ipsec add west-east
east# echo "initdone"

west# /testing/guestbin/swan-prep
west# ipsec start
west# ../../guestbin/wait-until-pluto-started
west# ipsec add west-east
west# echo "initdone"

west# ipsec route west-east
west# ipsec _kernel state
west# ipsec _kernel policy

# trigger acquire using UDP
west# echo 'TRIGGER' | nc -u -w 1 192.1.2.23 7 # east
west# ../../guestbin/wait-for-pluto.sh '^".*#2: initiator established Child SA'
east# ../../guestbin/ping-once.sh --up 192.1.2.45 # west
west# ../../guestbin/ping-once.sh --up 192.1.2.23 # east
# wait for larval state to clear; hack
west# ../../guestbin/wait-for.sh --no-match 'spi 0x00000000' ipsec _kernel state
west# ipsec _kernel state
west# ipsec _kernel policy

west# ipsec down west-east
west# ipsec _kernel state
west# ipsec _kernel policy
