name: Bug Report
title: What seems to be wrong?
type: bug
description: |
  Libreswan isn't behaving as expected.
body:
  - type: markdown
    attributes:
      value: |
        _Please remember that this is a volunteer project._<br>
        _If you have an urgent problem that cannot wait, consider one
        of the [commercial
        support](https://github.com/libreswan/libreswan/wiki/Support)
        options._
  - type: textarea
    attributes:
      label: Please Tell Us About Your System Configuration
      description: |
        - please start by filling in as many "Fields" (on the right) as possible
        - for connection problems, please describe the topology <br> i.e., which machines are involved, and what they are running (`uname -a`)
        - for build problems, please include `/etc/os-release` (when available).
        - if possible, include `ipsec.conf` (wrapped in markdown's tripple backticks)
        - please do not include screen grabs <br> Instead format console output using triple-backticks
      placeholder: Your system details
    validations:
      required: true
  - type: textarea
    attributes:
      label: Please Tell Us What Happened?
      description: |
        Please also tell us, what you think should happen.<br>
        - include relevant log output wrapped in triple-backticks
          + include the log of the connection being loaded <br> There should be no warnings!
          + include the entire IKE and Child exchange <br> Not just the last line
          + remove sensitive details; public addresses? and certificate IDs? <br> but keep as much information as possible
          + but do not include debug logs <br> _Initially, we're interested in the big picture_.
        - please do not include screen grabs <br> Instead format console output using triple-backticks
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
    validations:
      required: false
