config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	plutodebug=all,crypt
	dumpdir=/tmp

conn %default
	left=192.1.2.45
	leftid=%fromcert
	leftrsasigkey=%cert
	right=192.1.2.23
	rightid=%fromcert
	rightrsasigkey=%cert
	authby=rsasig

conn east
	rightcert=east
	intermediate=yes
	ike=aes128-sha2-dh31;addke1=ml_kem_1024

conn west
	leftcert=west
	intermediate=yes
	ike=aes128-sha2-dh31;addke1=ml_kem_1024
