# /etc/ipsec.conf - Libreswan IPsec configuration file

config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	plutodebug=all
	dumpdir=/tmp

conn westnet-eastnet-ikev2
	left=192.1.2.45
	leftid="C=CH, O=strongSwan, CN=strongWest"
	leftsubnet=192.0.1.0/24
	leftcert=strongWest
	right=192.1.2.23
	rightsubnet=192.0.2.0/24
	rightid="C=CH, O=strongSwan, CN=strongEast"
	authby=mldsa
	leftsendcert=always
	rightsendcert=always
	fragmentation=yes
