config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	plutodebug=all
	dumpdir=/tmp

conn rise-set
	left=198.18.1.12
	leftid="@rise"
	right=198.18.1.15
	rightid="@set"
	authby=secret
	type=transport
	compress=no
	phase2=esp
