#!/usr/bin/perl

open(CALC, "calc-reciprocal-out.txt") || die "failed to open calc: $!\n";

$file="../../../include/modulus_reciprocals.h";
open(RECIPROCALS, ">$file") || die "Can not write to $file: $!\n";

print RECIPROCALS "/*\n * this file generated by testing/crypto/reducent-01/gen-reciprocal.pl \n";
print RECIPROCALS " * ";
print RECIPROCALS "by ".$ENV{'LOGNAME'}." on ";
print RECIPROCALS `date`;
print RECIPROCALS " */\n\n";

while(<CALC>) {
  chop;

  if(/^Group (.*) Tries/) {
    $groupnum=$1;
    next;
  }

  if(/^Reciprocal: (.*)$/) {
    $reciprocal=$1;

    $reciprocal =~ y/a-f/A-Z/;
    
    $bitlen = length($reciprocal) * 4;
    $i = 0;
    $str = substr($reciprocal, 0, 8);
    substr($reciprocal, 0, 8)="";
    print RECIPROCALS sprintf("#define MODP%d_RECIPROCAL \\\n", $bitlen);
    print RECIPROCALS "   \"";
    while(length($str) > 0) {
      print RECIPROCALS "$str ";
      $i++;
      $str = substr($reciprocal, 0, 8);
      substr($reciprocal, 0, 8)="";

      if($i==8 && length($str)) {
	print RECIPROCALS "\" \\\n   \"";
	$i=0;
      }

    }
    print RECIPROCALS "\"\n\n";
  }
}
