# -*- mode: sh; sh-shell: sh -*-
. /etc/defaults/rc.conf

rc_configured=YES
no_swap=YES
savecore=NO
postfix=NO
autofs=YES
newsyslog=YES

. /etc/rc.hostname

dhcpcd=YES
dhcpcd_flags="vioif${dhcp_ethN} --nogateway --waitip=4 --ipv4only --oneshot --noarp"

test "${ipv4_eth0}" && ifconfig_vioif0="inet ${ipv4_eth0} ; inet6 ${ipv6_eth0}"
test "${ipv4_eth1}" && ifconfig_vioif1="inet ${ipv4_eth1} ; inet6 ${ipv6_eth1}"
test "${ipv4_eth2}" && ifconfig_vioif2="inet ${ipv4_eth2} ; inet6 ${ipv6_eth2}"

defaultroute=${ipv4_gw}
defaultroute6=${ipv6_gw}

# Move this hack where?
if ${forwarding} ; then
    for ctl in net.inet.ip.forwarding net.inet6.ip6.forwarding ; do
	if test "$(sysctl -n ${ctl})" -eq 0 ; then
            sysctl -w ${ctl}=1
	fi
    done
fi
