#####
##### GENERATED BY testing/utils/host-to-host.sh
#####   do not modify

east# /testing/guestbin/swan-prep
east# ipsec start
east# ../../guestbin/wait-until-pluto-started
east# ipsec whack --impair suppress_retransmits
east# ipsec add westnet-eastnet
east# echo "initdone"

west# /testing/guestbin/swan-prep
west# ipsec start
west# ../../guestbin/wait-until-pluto-started
west# ipsec whack --impair suppress_retransmits
west# ipsec add westnet-eastnet
west# echo "initdone"

west# ipsec up westnet-eastnet
west# ipsec _kernel state
west# ipsec _kernel policy
rise# ../../guestbin/ping-once.sh --up 192.0.1.15
set# ../../guestbin/ping-once.sh --up 192.0.2.12
west# ipsec whack --trafficstatus
west# ipsec down westnet-eastnet
west# ipsec _kernel state
