#!/bin/sh

TESTNAME=$(cat /tmp/swan.current)

if [ -f /testing/pluto/${TESTNAME}/testparams.sh ]; then
    . /testing/pluto/${TESTNAME}/testparams.sh
else
    echo "Unknown or broken test case /testing/pluto/${TESTNAME}"
    exit 1
fi

if [ -f /testing/pluto/${TESTNAME}/$(hostname)run.sh ]; then
    . /testing/pluto/${TESTNAME}/$(hostname)run.sh
    echo "$(hostname) completed ${TESTNAME}"
else
    echo "broken test - missing /testing/pluto/${TESTNAME}/$(hostname)run.sh"
    exit 1
fi
