#!/bin/sh

# we run with -x so : works instead of echo for output (not logging)
set -eux

if [ -r kvmsetup.sh.sample ]; then
    cat <<EOF

${PWD} is a top-level source directory.
Not CDing to /source

EOF
else
    cd /source
fi

if [ -f /usr/libexec/ipsec/pluto ]; then
    : ABORT: existing pluto found at /usr/libexec/ipsec/pluto
    exit 1
fi

# we don't trust all makefile dependancies, esp lib/
rm -rf OBJ.linux.* modobj

# sometimes left behind - an error in "make check"
# "make programs" doesn't leave these behind.
rm -f lib/libipsecconf/lex.yy.c lib/libipsecconf/parser.dot \
    lib/libipsecconf/parser.output lib/libipsecconf/parser.tab.c \
    lib/libipsecconf/parser.tab.h
# these are not wiped when running rm -rf OBJ*
# "make programs" doesn't leave these behind.
rm -f lib/libswan/Makefile.depend lib/libipsecconf/Makefile.depend \
    lib/libwhack/Makefile.depend programs/pluto/Makefile.depend

echo ">>> $0 on $(hostname) at $(date)" >>compile-log.txt

if make programs module >>compile-log.txt 2>&1; then
    : 'make programs module' success
else
    status=$?
    tail -20 compile-log.txt
    : 'make programs module' failed: ${status}; see compile-log.txt for details
    exit ${status}
fi

echo "$0 finished on $(hostname) at $(date)"
