#!/bin/sh

if [ -z "${1}" ]; then
    echo "No testname specified, use list to --list all test names"
    exit 1
fi

if [ "${1}" == "list" -o "${1}" == "--list" ]; then
    olddir=$(pwd)
    cd /vol/git/libreswan/testing/pluto
    ls -d *
    cd ${olddir}
    exit
fi

if [ ! -f /testing/pluto/${1}/testparams.sh ]; then
    echo "Unknown or broken test case /testing/pluto/${1}"
    exit 1
else
    . /testing/pluto/${1}/testparams.sh
    echo "${TESTNAME} selected"
fi
