
ifdef obj
my_inc_base = $(obj)
else
my_inc_base = .
O_TARGET := ocfnull.o
endif

obj-$(CONFIG_OCF_OCFNULL)       += $(obj-base)ocfnull.o

EXTRA_CFLAGS += -I$(my_inc_base)/.


ifdef obj
my_inc_base = $(obj)
else
my_inc_base = .
O_TARGET := ocfnull.o
endif

obj-$(CONFIG_OCF_OCFNULL)       += $(obj-base)ocfnull.o

EXTRA_CFLAGS += -I$(my_inc_base)/.

