'\" t
.\"     Title: SETUP
.\"    Author: Paul Wouters
.\" Generator: DocBook XSL Stylesheets v1.77.1 <http://docbook.sf.net/>
.\"      Date: 12/16/2012
.\"    Manual: Executable programs
.\"    Source: libreswan
.\"  Language: English
.\"
.TH "SETUP" "8" "12/16/2012" "libreswan" "Executable programs"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipsec_setup \- wrapper routine to the Libreswan init system
.SH "DESCRIPTION"
.PP
\fIsetup\fR
is called (via
\fIipsec setup\fR) by the system administrator to perform init system related tasks to Libreswan, such as start, stop, status, reload, etc for the Internet Keying Exchange (IKE) daemon pluto\&. It is available for backwards compatibility with Openswan and FreeS/WAN\&.
.SH "SUPPORTED INIT SYSTEMS"
.PP
Currently, the classic initscripts (sysv) and systemd are supported\&. Support for upstart will be added soon\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(8),
\fBsystemd.service\fR(5),
\fBipsec\fR(8),
\fBipsec__realsetup\fR(8),
\fBipsec__plutorun\fR(8)
\&.
.SH "HISTORY"
.PP
Man page written for the Linux FreeS/WAN project by Michael Richardson\&. Original program by Henry Spencer\&. Updated to
\m[blue]\fBhttp://www\&.libreswan\&.org/\fR\m[]> by Paul Wouters
.SH "AUTHOR"
.PP
\fBPaul Wouters\fR
.RS 4
placeholder to suppress warning
.RE
