connections {
	westnet-eastnet-ikev2 {
		proposals=aes-sha2_256-modp2048
		version=2
		local_addrs=192.1.3.33
		mobike=yes
		remote_addrs=192.1.2.23
		children {
			westnet-eastnet-ikev2 {
				start_action=none
				local_ts=198.18.66.0/24
				remote_ts=192.0.2.0/24
			}
			
		}
		local-0 {
			auth = psk
			id = @north
		}
		remote-0 {
			auth = psk
			id = @east
		}
	}
}
pools {
}
authorities {
}
secrets {
	ike- {
		secret = "ABCDEFGHIJ12345"
	}
}
