# load environment
if test -r $HOME/.kvm_env ; then
   . $HOME/.kvm_env
fi

# don't flood output with bracket characters
bind 'set enable-bracketed-paste off'

# single simple path
# - on BSD /bin and /usr/bin are different beasts
# - on NetBSD /usr/pkg/bin contains extra stuff
# - on OpenBSD/FreeBSD it is /usr/local/bin
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/pkg/bin:/usr/pkg/sbin:/usr/local/bin:/usr/local/sbin:/testing/guestbin

# editor
export EDITOR=vim

# git stuff
export GIT_PS1_SHOWDIRTYSTATE=true
alias git-log-p='git log --pretty=format:"%h %ad%x09%an%x09%s" --date=short'

# stop systemd adding control characters
export LC_CTYPE=C
export SYSTEMD_COLOURS=false

# don't wander into the weeds looking for debug info
unset DEBUGINFOD_URLS

# include status in the prompt when non-zero
PS1='['"${KVM_PLATFORM:-\u}"'@\h \W$(s=${?#0};echo "${s:+ $s}")]\$ '

# Force OBJDIR into /var/tmp
export OBJDIR=/var/tmp/OBJDIR
