
ifdef obj
my_inc_base = $(obj)
else
my_inc_base = .
O_TARGET := cryptosoft.o
endif

obj-$(CONFIG_OCF_CRYPTOSOFT) += $(obj-base)cryptosoft.o

EXTRA_CFLAGS += -I$(my_inc_base)/.


ifdef obj
my_inc_base = $(obj)
else
my_inc_base = .
O_TARGET := cryptosoft.o
endif

obj-$(CONFIG_OCF_CRYPTOSOFT) += $(obj-base)cryptosoft.o

EXTRA_CFLAGS += -I$(my_inc_base)/.

