connections {
	westnet-eastnet-ikev1 {
		#obsoleted option leftnexthop=192.1.2.23
		#=Right
		#obsoleted option rightnexthop=192.1.2.45
		#ike=camellia256-sha1-modp2048!
		version=1
		local_addrs=192.1.2.23
		remote_addrs=192.1.2.45
		proposals=aes256-sha1-modp2048
		children {
			westnet-eastnet-ikev1 {
				start_action=none
				esp_proposals=camellia256-sha1-modp2048
				remote_ts=192.0.1.0/24
				local_ts=192.0.2.0/24
			}
			
		}
		local-0 {
			auth = psk
			id = @east
		}
		remote-0 {
			auth = psk
			id = @west
		}
	}
}
pools {
}
authorities {
}
secrets {
	ike-@east@west {
		secret = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
		id-0=@east
		id-1=@west
	}
}
