/* exports from code generated by lex from parser.l
 * The generated code already declares these so it shouldn't include this header.
 *
 * Copyright (C) 2013 D. Hugh Redelmeier
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.  See <https://www.gnu.org/licenses/gpl2.txt>.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 */

#ifndef IPSECCONF_SCANNER_H
#define IPSECCONF_SCANNER_H

struct jambuf;
struct parser;

extern int yylex(struct parser *parser);

/* "<FILE>:<LINE>: " */
void jam_scanner_file_line(struct jambuf *buf);

#endif
