#####
##### GENERATED BY testing/utils/host-to-host.sh
#####   do not modify
#####

east# ../../guestbin/prep.sh
east# ipsec start
east# ../../guestbin/wait-until-pluto-started
east# ipsec add west-east
east# echo "initdone"

west# ../../guestbin/prep.sh
west# ipsec start
west# ../../guestbin/wait-until-pluto-started
west# ipsec add west-east
west# echo "initdone"

west# ipsec up west-east # sanitize-retransmits
west# ipsec _kernel state
west# ipsec _kernel policy
east# ../../guestbin/ping-once.sh --up 2001:db8:1:2::45 # west
west# ../../guestbin/ping-once.sh --up 2001:db8:1:2::23 # east

west# ipsec down west-east
west# ipsec _kernel state
west# ipsec _kernel policy
