connections {
	westnet-eastnet-ikev2 {
		#=Right
		fragmentation=yes
		version=2
		local_addrs=192.1.2.23
		remote_addrs=192.1.2.45
		proposals=aes128-sha1-modp2048
		children {
			westnet-eastnet-ikev2 {
				start_action=none
				esp_proposals=aes128-sha1-modp2048
			}
			
		}
		local-0 {
			auth = psk
			id = @east
		}
		remote-0 {
			auth = psk
			id = @west
		}
	}
}
pools {
}
authorities {
}
secrets {
	ike-@east@west {
		secret = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
		id-0=@east
		id-1=@west
	}
}
