connections {
	westnet-eastnet-ikev2 {
		version=2
		local_addrs=192.1.2.45
		remote_addrs=192.1.2.23
		reauth_time = 20s
		children {
			westnet-eastnet-ikev2 {
				start_action=none
				local_ts=192.0.1.0/24
				remote_ts=192.0.2.0/24
			}
		}
		local-0 {
			auth = psk
			id = @west
		}
		remote-0 {
			auth = psk
			id = @east
		}
	}
}
pools {
}
authorities {
}
secrets {
	ike-@east@west {
		secret = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
		id-0=@east
		id-1=@west
	}
}
