connections {
	san {
		#rightca="%any"
		#leftca="%any"
		#rightid="C=CA, ST=Ontario, L=Toronto, O=Libreswan, OU=Test Department, CN=east.testing.libreswan.org, E=user-east@testing.libreswan.org"
		aggressive=yes
		proposals=aes-sha1-modp1536, default
		version=1
		local_addrs=192.1.2.45
		send_cert=always
		remote_addrs=192.1.2.23
		#rightsend_cert=always
		children {
			san {
				start_action=none
				esp_proposals=aes-sha1-modp1536, default
			}
			
		}
		local-0 {
			auth = pubkey
			cacerts = /etc/strongswan/ipsec.d/cacerts/mainca.crt
			certs = /etc/strongswan/swanctl/x509/west.crt
			id = "C=CA, ST=Ontario, L=Toronto, O=Libreswan, OU=Test Department, CN=west.testing.libreswan.org, E=user-west@testing.libreswan.org"
		}
		remote-0 {
			auth = pubkey
			id = "C=CA, ST=Ontario, L=Toronto, O=Libreswan, OU=Test Department, CN=east.testing.libreswan.org, E=user-east@testing.libreswan.org"
		}
	}
}
pools {
}
authorities {
}
secrets {
	rsa- {
		file=/etc/strongswan/swanctl/rsa/west.key
	}
}
