'\" t
.\"     Title: IPSEC
.\"    Author: Henry Spencer
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 03/17/2014
.\"    Manual: Executable programs
.\"    Source: libreswan
.\"  Language: English
.\"
.TH "IPSEC" "8" "03/17/2014" "libreswan" "Executable programs"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipsec \- invoke IPsec utilities
.SH "SYNOPSIS"
.HP \w'\fBipsec\fR\ 'u
\fBipsec\fR \fIcommand\fR [\fIargument\fR...] \fIipsec\fR \-\-help
.br
\fIipsec\fR \-\-version
.br
\fIipsec\fR \-\-directory
.SH "DESCRIPTION"
.PP
\fIipsec\fR
invokes any of several utilities involved in controlling the IPsec encryption/authentication system, running the specified
\fIcommand\fR
with the specified
\fIargument\fRs as if it had been invoked directly\&. This largely eliminates possible name collisions with other software, and also permits some centralized services\&.
.PP
\fBipsec \-\-help\fR
lists the available commands\&. Most have their own manual pages, e\&.g\&.
\fBipsec_auto\fR(8)
for
\fIauto\fR\&.
.PP
\fBipsec \-\-version\fR
outputs the software version\&. A version code of the form ``U\fIxxx\fR/K\fIyyy\fR\*(Aq\*(Aq indicates that the user\-level utilities are version
\fIxxx\fR
but the kernel portion appears to be version
\fIyyy\fR
(this form is used only if the two disagree)\&. For the NETKEY/XFRM stack, the kernel version is used, always displaying the U/K split\&.
.PP
\fBipsec \-\-directory\fR
reports where
\fBipsec\fR
thinks the IPsec commands are stored\&.
.SH "COMMANDS"
.PP
To get a list of supported commands, use ipsec \-\-help\&. A few of the commonly used commands are described below
.PP
\fBipsec setup start|stop|restart\fR
maps to the host init system\&. Supported init systems are sysv, systemd, upstart and openrc\&.
.PP
\fBipsec barf\fR
dumps the internal system status to stdout for debugging
.PP
\fBipsec auto \fR
is used to manually add, remove, up or down connections\&. For more information see \*(Aqman ipsec_auto
.PP
\fBipsec whack\fR
is used to communicate direct commands to the pluto daemon using the whack interface\&. For more information see \*(Aqman ipsec_pluto\*(Aq
.PP
\fBipsec initnss\fR
initialises the NSS database that contains all the X\&.509 certificate information and private RSA keys
.PP
\fBipsec import\fR
is used to import PKCS#12 X\&.509 files into the NSS database
.SH "FILES"
.PP
/usr/local/libexec/ipsec usual utilities directory
.SH "SEE ALSO"
.PP
ipsec\&.\fBconf\fR(5), ipsec\&.\fBsecrets\fR(5),
\fBipsec_auto\fR(8),
\fBipsec_setup\fR(8),
\fBipsec_showhostkey\fR(8)
.SH "AUTHOR"
.PP
\fBHenry Spencer\fR
.RS 4
.RE
