# /etc/ipsec.conf - Libreswan IPsec configuration file

config setup
	logfile=/tmp/pluto.log
	logtime=yes
	logappend=no
	dumpdir=/tmp
	plutodebug=all

conn west-to-east
	authby=secret
	leftid=@east
	rightid=@west
	left=192.1.2.23
	right=192.1.2.45
	leftsubnet=192.0.2.0/24
	rightsubnet=192.0.1.0/24
	auto=add
