# /etc/ipsec.conf - Libreswan IPsec configuration file

config setup
	logfile=/tmp/pluto.log
	logtime=yes
	logappend=no
	dumpdir=/tmp
	plutodebug=all

conn distraction
	authby=secret
	leftid=@west
	rightid=@east
	left=192.1.2.45
	right=192.1.2.23
	leftsubnet=192.0.1.0/24
	rightsubnet=192.0.2.0/24

conn west-to-east
	also=distraction
	auto=ondemand
