config setup
	# put the logs in /tmp for the UMLs, so that we can operate
	# without syslogd, which seems to break on UMLs
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	plutodebug=all
	dumpdir=/tmp

conn westnet-eastnet-ikev2
        # Left security gateway, subnet behind it, next hop toward right.
        leftckaid=@@WEST_CKAID@@
        leftid=%fromcert
        # Right security gateway, subnet behind it, next hop toward left.
        rightckaid=@@EAST_CKAID@@
	rightid=%fromcert
	left=192.1.2.45
	right=192.1.2.23
	leftsubnet=192.0.1.0/24
	rightsubnet=192.0.2.0/24
