connections {
	westnet-eastnet-ikev2 {
		fragmentation=yes
		proposals=aes-sha256-modp2048
		version=2
		local_addrs=192.1.2.45
		remote_addrs=192.1.2.23
		children {
			westnet-eastnet-ikev2 {
				start_action=none
				esp_proposals=aes-sha256-modp2048
				local_ts=192.0.1.0/24
				remote_ts=192.0.2.0/24
			}
			
			westnet-eastnet2-ikev2 {
				start_action=none
				esp_proposals=aes-sha256-modp2048
				local_ts=8.8.8.8/32
				remote_ts=9.9.9.9/32
			}
			
		}
		local-0 {
			auth = psk
			id = @west
		}
		remote-0 {
			auth = psk
			id = @east
		}
	}
}
pools {
}
authorities {
}
secrets {
	ike-@east@west {
		secret = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
		id-0=@east
		id-1=@west
	}
}
