#!/bin/sh

bindir=$(dirname $0)

basedir=testing/pluto/$(basename $0 .sh)

. ${bindir}/../kvm/bin/topology.sh

# connectivity HOST name-of-dest ...

connectivity()
{
    local source=$1 ; shift
    echo "# ${source} to $@" >> ${sh}
    for dest in "$@" ; do
	dest_ip=$(eval echo \$${dest})
	echo "${source}# ../../guestbin/ping-once.sh --up ${dest_ip} # ${dest}" >> ${sh}
    done
}

# where am I
if test ! testing/pluto ; then
    echo confused $basedir
    exit 1
fi

do_not_modify()
{
    echo "#####"
    echo "##### GENERATED BY $0"
    echo "#####   do not modify"
}

for platform in ${platforms} ; do

    dir=${basedir}-${platform}
    echo ${dir}

    mkdir -p ${dir}

    cat <<EOF > ${dir}/description.txt
connectivity and sniff test for ${platform}
EOF
    do_not_modify >> ${dir}/description.txt
    cat <<EOF >> ${dir}/description.txt
test connectivity between:
- EAST and WEST+NIC+RISE
- WEST and EAST+NIC+RISE
- RISE and SET+EAST
- SET and RISE+WEST
- NORTH and NIC+EAST+WEST
test pluto between:
- RISE and SET
EOF

    for host in ${hosts} ; do
	touch ${dir}/${host}.console.txt
    done

    case ${platform} in
	netbsd )  eth=vioif ;;
	openbsd ) eth=vio ;;
	freebsd ) eth=vtnet ;;
	* )       eth=eth ;;
    esac

    # start again
    sh=${dir}/all.nic
    for host in ${hosts} ; do
	case ${host} in
	    nic ) ;;
	    * )	sh=${sh}-${platform}${host} ;;
	esac
    done
    sh=${sh}.sh
    rm -f ${sh}
    do_not_modify > ${sh}

    echo "" >> ${sh}
cat <<EOF > ${sh}
nic# : make certain NIC is running
EOF

    # bring up all the networks

    for host in east west rise set north ; do
	echo "" >> ${sh}
	cat <<EOF >> ${sh}
${host}# ifconfig ${eth}0 | grep -e 'inet ' -e 'inet6 .*2001:'
${host}# ifconfig ${eth}1 | grep -e 'inet ' -e 'inet6 .*2001:'
EOF
    done

    # connectivity

    connectivity east west_internet4 nic_internet4 north_nicnet4 rise_eastnet4
    connectivity west east_internet4 nic_internet4 north_nicnet4  set_westnet4

    connectivity rise east_eastnet4 set_darknet4
    connectivity set  west_westnet4 rise_darknet4

    connectivity north road_nicnet4 nic_nicnet4 nic_internet4 east_internet4 west_internet4

    connectivity road north_nicnet4 nic_nicnet4 nic_internet4 east_internet4 west_internet4

done
