#!/bin/sh

basedir=testing/pluto/$(basename $0 .sh)
hosts="east west rise set north" # nic
# same platforms as KVM
platforms=$(ls -d1 testing/kvm/platform/[a-z]*/ | cut -d/ -f4)

# public network, name is arbitrary
pubnet=192.1.2
# another arbitrary network name
sunnet=198.18.1
# NIC's private network - gets NATed
nicnet=192.1.3
# EAST's private network
eastnet=192.0.2
# WEST's private network
westnet=192.0.1
# NORTH's private network
northnet=192.0.3

# HOST_NETWORK

nic_nicnet=${nicnet}.254
nic_pubnet=${pubnet}.254

east_eastnet=${eastnet}.254
east_pubnet=${pubnet}.23

west_pubnet=${pubnet}.45
west_westnet=${westnet}.254

north_nicnet=${nicnet}.33
north_northnet=${northnet}.254

road_nicnet=${nicnet}.209

rise_eastnet=${eastnet}.12
rise_sunnet=${sunnet}.12

set_sunnet=${sunnet}.15
set_westnet=${westnet}.15

in=

# connectivity HOST name-of-dest ...

connectivity()
{
    local source=$1 ; shift
    echo "# ${source} to $@" >> ${in}
    for dest in "$@" ; do
	dest_ip=$(eval echo \$${dest})
	echo "${source}# ../../guestbin/ping-once.sh --up ${dest_ip} # ${dest}" >> ${in}
    done
}

# where am I
if test ! testing/pluto ; then
    echo confused $basedir
    exit 1
fi

do_not_modify()
{
    echo "#####"
    echo "##### GENERATED BY $0"
    echo "#####   do not modify"
}

for platform in ${platforms} ; do

    dir=${basedir}-${platform}
    echo ${dir}

    mkdir -p ${dir}

    cat <<EOF > ${dir}/description.txt
connectivity and sniff test for ${platform}
EOF
    do_not_modify >> ${dir}/description.txt
    cat <<EOF >> ${dir}/description.txt
test connectivity between:
- EAST and WEST+NIC+RISE
- WEST and EAST+NIC+RISE
- RISE and SET+EAST
- SET and RISE+WEST
- NORTH and NIC+EAST+WEST
test pluto between:
- RISE and SET
EOF

    for host in ${hosts} nic ; do
	touch ${dir}/${host}.console.txt
    done

    case ${platform} in
	netbsd )  eth=vioif ;;
	openbsd ) eth=vio ;;
	freebsd ) eth=vtnet ;;
	alpine )  eth=eth ;;
	* )       eth=eth ;;
    esac

    # start again
    in=${dir}/east-west-${platform}rise-${platform}set-nic-${platform}north.in
    rm -f ${in}
    do_not_modify > ${in}

    echo "" >> ${in}
cat <<EOF > ${in}
nic# : make certain NIC is running
EOF

    # bring up all the networks

    for host in east west rise set north ; do
	echo "" >> ${in}
	cat <<EOF >> ${in}
${host}# ifconfig ${eth}0
${host}# ifconfig ${eth}1
EOF
    done

    # connectivity

    connectivity east west_pubnet nic_pubnet north_nicnet rise_eastnet
    connectivity west east_pubnet nic_pubnet north_nicnet set_westnet

    connectivity rise east_eastnet set_sunnet
    connectivity set west_westnet rise_sunnet

    connectivity north north_northnet nic_nicnet nic_pubnet east_pubnet west_pubnet

    # sniff test ipsec

    cat <<EOF > ${dir}/ipsec.secrets
@east @west @rise @set @north @road : PSK "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
EOF

    cat <<EOF > ${dir}/ipsec.conf
config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	plutodebug=all
	dumpdir=/tmp
conn rise-set
	leftid=@rise
	rightid=@set
	authby=secret
	left=${rise_sunnet}
	right=${set_sunnet}
        leftsubnet=${eastnet}.0/24
        rightsubnet=${westnet}.0/24
EOF

    for host in rise set ; do
	echo "" >> ${in}
	cat <<EOF >> ${in}
${host}# ../../guestbin/prep.sh
${host}# ipsec initnss
${host}# ipsec start
${host}# ../../guestbin/wait-until-pluto-started
${host}# ipsec add rise-set
EOF
    done
    cat <<EOF >> ${in}
rise# ipsec up rise-set
EOF

done
