#!/bin/sh

basedir=testing/pluto/$(basename $0 .sh)
hosts="east west rise set"
oss="alpine debian netbsd freebsd openbsd fedora"

# where am I
if test ! testing/pluto ; then
    echo confused $basedir
    exit 1
fi

for os in ${oss} ; do

    dir=${basedir}-${os}
    echo ${dir}

    mkdir -p ${dir}

    cat <<EOF > ${dir}/description.txt
sniff test ${os}; generated by $0
- test network connectivity between RISE and SET
  and EAST and WEST
- try starting pluto
EOF

    for host in ${hosts} ; do
	touch ${dir}/${host}.console.txt
    done

    case $os in
	netbsd )  eth=vioif ; ifconfig=ifconfig ;;
	openbsd ) eth=vio   ; ifconfig=ifconfig ;;
	freebsd ) eth=vtnet ; ifconfig=ifconfig ;;
	alpine )  eth=eth ; ifconfig=ifconfig ;;
	* )       eth=eth   ; ifconfig="ip link set" ;;
    esac

    # start again
    in=${dir}/east-west-${os}rise-${os}set.in
    rm -f ${in}
    echo "# this script was generated by $0" > ${in}

    # bring up all the networks

    for host in east west ; do
	echo "" >> ${in}
	cat <<EOF >> ${in}
${host}# ../../guestbin/ip.sh addr show eth0
${host}# ../../guestbin/ip.sh link set eth0 up
${host}# ../../guestbin/ip.sh addr show eth1
${host}# ../../guestbin/ip.sh link set eth1 up
EOF
    done

    for host in rise set ; do
	echo "" >> ${in}
	cat <<EOF >> ${in}
${host}# ${ifconfig} ${eth}1
${host}# ${ifconfig} ${eth}1 up
${host}# ${ifconfig} ${eth}2
${host}# ${ifconfig} ${eth}2 up
EOF
    done

    # check connectivity

    echo "" >> ${in}
    cat <<EOF >> ${in}
rise# ../../guestbin/ping-once.sh --up 198.18.1.15  # SET
rise# ../../guestbin/ping-once.sh --up 192.0.2.254  # EAST
EOF

    echo "" >> ${in}
    cat <<EOF >> ${in}
set# ../../guestbin/ping-once.sh --up 198.18.1.12  # RISE
set# ../../guestbin/ping-once.sh --up 192.0.1.254  # WEST
EOF

    for host in rise set ; do
	echo "" >> ${in}
	cat <<EOF >> ${in}
${host}# ../../guestbin/prep.sh
${host}# ipsec initnss
${host}# ipsec pluto --selftest
EOF
    done

done
