#!/bin/bash

# host-to-host-{transport,tunnel}-{freebsd,linux,netbsd,openbsd}
# host-to-host-tunnel-forward-{freebsd,linux,netbsd,openbsd}
# host-to-host-{transport,tunnel}-ondemand-{freebsd,linux,netbsd,openbsd}

bindir=$(dirname $0)

basedir=testing/pluto/$(basename $0 .sh)

. ${bindir}/../kvm/bin/topology.sh

# where am I
if test ! -d testing/pluto ; then
    echo confused $basedir
    exit 1
fi

do_not_modify()
{
    echo "#####"
    echo "##### GENERATED BY $0"
    echo "#####   do not modify"
}

for platform in ${platforms} ; do

    case ${platform} in
	alpine | debian | fedora ) continue ;;
    esac

    case ${platform} in
	linux ) stack="XFRM" ;;
	* )     stack="PFKEYv2" ;;
    esac

    for mode in transport transport-ondemand tunnel tunnel-forward tunnel-ondemand ; do

	dir=${basedir}-${mode}-${platform}
	echo ${dir}

	mkdir -p ${dir}

	# tunnel is IPv6, transport is IPv4
	# tunnel-forward is IPv4 with rise/set behind the east=west tunnel
	# *-ondemand traps traffic and waits for an acquire to initiate

	modeline='#type='
	leftsubnetline='#leftsubnet='
	rightsubnetline='#rightsubnet='

	case ${mode} in
	    transport )
		west=${west_internet4}
		east=${east_internet4}
		rise=${rise_eastnet4}
		set=${set_westnet4}
		modeline="type=transport"
		what="host-to-host transport mode"
		conn=west-east
		hosts=${platform}east-${platform}west
		westimpair=
		trigger=
		;;
	    transport-ondemand )
		west=${west_internet4}
		east=${east_internet4}
		rise=${rise_eastnet4}
		set=${set_westnet4}
		modeline="type=transport"
		what="ondemand host-to-host transport mode"
		conn=west-east
		hosts=${platform}east-${platform}west
		westimpair="west# ipsec whack --impair suppress_retransmits"
		trigger="west# echo 'TRIGGER' | nc -u -w 1 ${east} 7"
		;;
	    tunnel )
		west=${west_internet6}
		east=${east_internet6}
		rise=${rise_eastnet6}
		set=${set_westnet6}
		what="IPv6 host-to-host tunnel mode"
		conn=west-east
		hosts=${platform}east-${platform}west
		westimpair=
		trigger=
		;;
	    tunnel-forward )
		west=${west_internet4}
		east=${east_internet4}
		rise=${rise_eastnet4}
		set=${set_westnet4}
		leftsubnetline="leftsubnet=${westnet4}0/24"
		rightsubnetline="rightsubnet=${eastnet4}0/24"
		what="rise-east=TUNNEL=west-set"
		conn=westnet-eastnet
		hosts=${platform}east-${platform}rise-${platform}set-${platform}west
		westimpair="west# ipsec whack --impair suppress_retransmits"
		trigger=
		;;
	    tunnel-ondemand )
		west=${west_internet4}
		east=${east_internet4}
		rise=${rise_eastnet4}
		set=${set_westnet4}
		leftsubnetline="leftsubnet=${westnet4}0/24"
		rightsubnetline="rightsubnet=${eastnet4}0/24"
		what="rise-east=TUNNEL=west-set triggered by an acquire"
		conn=westnet-eastnet
		hosts=${platform}east-${platform}rise-${platform}set-${platform}west
		westimpair=
		trigger="set# echo 'TRIGGER' | nc -u -w 1 ${rise} 7"
		;;
	esac

	# linux disables IPv6 unless swan-prep is told not to

	case ${platform}-${mode} in
	    linux-tunnel ) prep="/testing/guestbin/swan-prep --46" ;;
	    linux-* )      prep="/testing/guestbin/swan-prep" ;;
	    * )            prep="../../guestbin/prep.sh" ;;
	esac

	cat <<EOF > ${dir}/description.txt
${stack} ${what} on $(echo ${platform} | sed -e 's/linux/Linux/' -e 's/freebsd/FreeBSD/' -e 's/netbsd/NetBSD/' -e 's/openbsd/OpenBSD/')
EOF
	do_not_modify >> ${dir}/description.txt

	cat <<EOF > ${dir}/ipsec.conf
config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	plutodebug=all
	dumpdir=/tmp

conn ${conn}
	left=${west}
	leftid="@west"
	right=${east}
	rightid="@east"
	authby=secret
	${modeline}
	${leftsubnetline}
	${rightsubnetline}
	compress=no
	phase2=esp
EOF

	cat <<EOF > ${dir}/ipsec.secrets
@west @east : PSK "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
EOF

	touch ${dir}/east.console.txt
	touch ${dir}/west.console.txt

	case ${mode} in
	    tunnel-forward | tunnel-ondemand )
		touch ${dir}/rise.console.txt
		touch ${dir}/set.console.txt
		;;
	esac

	rm -f ${dir}/all.*.sh
	sh=${dir}/all.${hosts}.sh
	do_not_modify > ${sh}
	cat <<EOF >> ${sh}

east# ${prep}
east# ipsec start
east# ../../guestbin/wait-until-pluto-started
east# ipsec whack --impair suppress_retransmits
east# ipsec add ${conn}
east# echo "initdone"

west# ${prep}
west# ipsec start
west# ../../guestbin/wait-until-pluto-started${westimpair:+
${westimpair}}
west# ipsec add ${conn}
west# echo "initdone"

EOF

	case ${mode} in
	    *-ondemand )
		cat <<EOF >> ${sh}
west# ipsec route ${conn}
west# ipsec _kernel state
west# ipsec _kernel policy

# trigger acquire using UDP
${trigger}
west# ../../guestbin/wait-for-pluto.sh '^".*#2: initiator established Child SA'
EOF
		;;
	    * )
		cat <<EOF >> ${sh}
west# ipsec up ${conn} # sanitize-retransmits
west# ipsec _kernel state
west# ipsec _kernel policy
EOF
		;;
	esac

	case ${mode} in
	    tunnel-forward )
		cat <<EOF >> ${sh}
rise# ../../guestbin/ping-once.sh --up ${set} # set
set# ../../guestbin/ping-once.sh --up ${rise} # rise
west# ipsec whack --trafficstatus
EOF
		;;
	    tunnel-ondemand )
		cat <<EOF >> ${sh}
rise# ../../guestbin/ping-once.sh --up ${set} # set
set# ../../guestbin/ping-once.sh --up ${rise} # rise
east# ipsec whack --trafficstatus
EOF
		;;
	    * )
		cat <<EOF >> ${sh}
west# ../../guestbin/ping-once.sh --up ${east} # east
EOF
		;;
	esac

	case ${mode} in
	    *-ondemand )
		cat <<EOF >> ${sh}
# wait for larval state to clear; hack
west# ../../guestbin/wait-for.sh --no-match 'spi 0x00000000' ipsec _kernel state
west# ipsec _kernel state
west# ipsec _kernel policy
EOF
		;;
	esac

	cat <<EOF >> ${sh}
west# ipsec down ${conn}
west# ipsec _kernel state
EOF

	case ${platform} in
	    openbsd )
		cat <<EOF > ${dir}/final.sh
ipsec delete ${conn}
ipsecctl -F
EOF
		;;
	    linux )
		cat <<EOF > ${dir}/final.sh
ipsec delete ${conn}
../../guestbin/ip.sh xfrm state flush
../../guestbin/ip.sh xfrm policy flush
EOF
		;;
	    * )
		cat <<EOF > ${dir}/final.sh
ipsec delete ${conn}
setkey -F
EOF
		;;
	esac

    done
done
