#!/bin/sh

# host-to-host-{transport,tunnel}-{freebsd,linux,netbsd,openbsd}
# host-to-host-tunnel-forward-{freebsd,linux,netbsd,openbsd}

bindir=$(dirname $0)

basedir=testing/pluto/$(basename $0 .sh)

. ${bindir}/../kvm/bin/topology.sh

# where am I
if test ! -d testing/pluto ; then
    echo confused $basedir
    exit 1
fi

do_not_modify()
{
    echo "#####"
    echo "##### GENERATED BY $0"
    echo "#####   do not modify"
}

for platform in ${platforms} ; do

    case ${platform} in
	alpine | debian | fedora ) continue ;;
    esac

    case ${platform} in
	linux ) stack="XFRM" ;;
	* )     stack="PFKEYv2" ;;
    esac

    for mode in transport tunnel tunnel-forward ; do

	dir=${basedir}-${mode}-${platform}
	echo ${dir}

	mkdir -p ${dir}

	# tunnel is IPv6, transport is IPv4
	# tunnel-forward is IPv4 with rise/set behind the east=west tunnel

	case ${mode} in
	    transport )
		west=${west_internet4}
		east=${east_internet4}
		modeline="	type=transport"
		what="host-to-host transport mode"
		conn=west-east
		hosts=${platform}east-${platform}west
		westimpair=
		;;
	    tunnel )
		west=${west_internet6}
		east=${east_internet6}
		modeline=
		what="IPv6 host-to-host tunnel mode"
		conn=west-east
		hosts=${platform}east-${platform}west
		westimpair=
		;;
	    tunnel-forward )
		west=${west_internet4}
		east=${east_internet4}
		modeline="	leftsubnet=${westnet4}.0/24
	rightsubnet=${eastnet4}.0/24"
		what="rise-east=TUNNEL=west-set"
		conn=westnet-eastnet
		hosts=${platform}east-${platform}rise-${platform}set-${platform}west
		westimpair="west# ipsec whack --impair suppress_retransmits"
		;;
	esac

	# linux disables IPv6 unless swan-prep is told not to

	case ${platform}-${mode} in
	    linux-transport )      prep="/testing/guestbin/swan-prep" ;;
	    linux-tunnel )         prep="/testing/guestbin/swan-prep --46" ;;
	    linux-tunnel-forward ) prep="/testing/guestbin/swan-prep" ;;
	    * )                    prep="../../guestbin/prep.sh" ;;
	esac

	cat <<EOF > ${dir}/description.txt
${stack} ${what} on $(echo ${platform} | sed -e 's/linux/Linux/' -e 's/freebsd/FreeBSD/' -e 's/netbsd/NetBSD/' -e 's/openbsd/OpenBSD/')
EOF
	do_not_modify >> ${dir}/description.txt

	cat <<EOF > ${dir}/ipsec.conf
config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	plutodebug=all
	dumpdir=/tmp

conn ${conn}
	left=${west}
	leftid="@west"
	right=${east}
	rightid="@east"
	authby=secret${modeline:+
${modeline}}
	compress=no
	phase2=esp
EOF

	cat <<EOF > ${dir}/ipsec.secrets
@west @east : PSK "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
EOF

	case ${platform} in
	    openbsd )
		cat <<EOF > ${dir}/final.sh
ipsec delete ${conn}
ipsecctl -F
EOF
		;;
	    linux )
		cat <<EOF > ${dir}/final.sh
ipsec delete ${conn}
../../guestbin/ip.sh xfrm state flush
../../guestbin/ip.sh xfrm policy flush
EOF
		;;
	    * )
		cat <<EOF > ${dir}/final.sh
ipsec delete ${conn}
setkey -F
EOF
		;;
	esac

	touch ${dir}/east.console.txt
	touch ${dir}/west.console.txt

	case ${mode} in
	    tunnel-forward )
		touch ${dir}/rise.console.txt
		touch ${dir}/set.console.txt
		;;
	esac

	rm -f ${dir}/all.*.sh
	sh=${dir}/all.${hosts}.sh
	do_not_modify > ${sh}
	cat <<EOF >> ${sh}

east# ${prep}
east# ipsec start
east# ../../guestbin/wait-until-pluto-started
east# ipsec whack --impair suppress_retransmits
east# ipsec add ${conn}
east# echo "initdone"

west# ${prep}
west# ipsec start
west# ../../guestbin/wait-until-pluto-started${westimpair:+
${westimpair}}
west# ipsec add ${conn}
west# echo "initdone"

west# ipsec up ${conn}
west# ipsec _kernel state
west# ipsec _kernel policy
EOF

	case ${mode} in
	    tunnel-forward )
		cat <<EOF >> ${sh}
rise# ../../guestbin/ping-once.sh --up ${set_westnet4}
set# ../../guestbin/ping-once.sh --up ${rise_eastnet4}
west# ipsec whack --trafficstatus
EOF
		;;
	    * )
		cat <<EOF >> ${sh}
west# ../../guestbin/ping-once.sh --up ${east}
EOF
		;;
	esac

	cat <<EOF >> ${sh}
west# ipsec down ${conn}
west# ipsec _kernel state
EOF

    done
done
