#!/bin/bash

# host-to-host-{transport,tunnel}-{freebsd,linux,netbsd,openbsd}
# host-to-host-tunnel-forward-{freebsd,linux,netbsd,openbsd}
# host-to-host-{transport,tunnel}-ondemand-{freebsd,linux,netbsd,openbsd}

bindir=$(dirname $0)

basedir=testing/pluto/$(basename $0 .sh)

. ${bindir}/../kvm/bin/topology.sh

# where am I
if test ! -d testing/pluto ; then
    echo confused $basedir
    exit 1
fi

do_not_modify()
{
    echo "#####"
    echo "##### GENERATED BY $0"
    echo "#####   do not modify"
    echo "#####"
}

up()
{
    echo
    cat <<EOF
west# ipsec up ${conn} # sanitize-retransmits
west# ipsec _kernel state
west# ipsec _kernel policy
EOF
}

ping_hosts()
{
    local mode=$1
    case ${mode} in
	tunnel-ondemand )
	    cat <<EOF >> ${sh}
rise# ../../guestbin/ping-once.sh --up ${set} # set
set# ../../guestbin/ping-once.sh --up ${rise} # rise
EOF
	    ;;
	tunnel-forward )
	    cat <<EOF >> ${sh}
rise# ../../guestbin/ping-once.sh --up ${set} # set
set# ../../guestbin/ping-once.sh --up ${rise} # rise
EOF
	    ;;
	* )
	    cat <<EOF >> ${sh}
west# ../../guestbin/ping-once.sh --up ${east} # east
EOF
	    ;;
    esac
}

down()
{
    echo
    cat <<EOF
west# ipsec down ${conn}
west# ipsec _kernel state
west# ipsec _kernel policy
EOF
}

stop()
{
    cat <<EOF
ipsec stop
EOF
}

delete()
{
    echo
cat <<EOF
ipsec delete ${conn}
EOF
    case ${platform} in
	openbsd )
	    cat <<EOF
ipsec delete ${conn}
ipsecctl -F
EOF
	    ;;
	linux )
	    cat <<EOF
ipsec delete ${conn}
../../guestbin/ip.sh xfrm state flush
../../guestbin/ip.sh xfrm policy flush
EOF
	    ;;
	* )
	    cat <<EOF
setkey -F
EOF
	    ;;
    esac
}

ondemand_child=0

ondemand()
{
    local trigger=$1
    case ${trigger} in
	west-*-east ) from=west ; to=${east} ; name=east ;;
	set-*-rise  ) from=set  ; to=${rise} ; name=rise ;;
	* ) echo confused by ${trigger} 1>&2 ;;
    esac
    echo
    case ${trigger} in
	*-udp7-* )
	    cat <<EOF
# trigger acquire using UDP
${from}# echo 'TRIGGER' | nc -u -w 1 ${to} 7 # ${name}
EOF
	    ;;
	*-udp0-* )
	    # XXX: this only works on Linux; on BSD 0 is rejected by
	    # both NC (unknown port) and the kernel (connect(2)
	    # fails).
	    cat <<EOF
# trigger acquire using UDP
${from}# socat -t0 - UDP:${to}:0 < /dev/null # ${name} - sends EOF?
EOF
	    ;;
	*-ping-* )
	    cat <<EOF
# trigger acquire using PING
${from}# ../../guestbin/ping-once.sh --down ${to} # ${name}
EOF
	    ;;
	west-iping-east )
	    cat <<EOF
# trigger acquire using PING -I SOURCE
west# ../../guestbin/ping-once.sh --down -I ${west_westnet} ${east} # east
EOF
	    ;;
	* )
	    echo confused by ${trigger} 1>&2
	    ;;
    esac
    ondemand_child=$((ondemand_child + 2))
    cat <<EOF
west# ../../guestbin/wait-for-pluto.sh '^".*#${ondemand_child}: initiator established Child SA'
EOF
}

for platform in ${platforms} ; do

    case ${platform} in
	alpine | debian | fedora ) continue ;;
    esac

    case ${platform} in
	linux ) stack="XFRM" ;;
	* )     stack="PFKEYv2" ;;
    esac

    for mode in transport transport-ondemand tunnel tunnel-forward tunnel-ondemand ; do

	ondemand_child=0
	dir=${basedir}-${mode}-${platform}
	echo ${dir}

	mkdir -p ${dir}

	# tunnel is IPv6, transport is IPv4
	# tunnel-forward is IPv4 with rise/set behind the east=west tunnel
	# *-ondemand traps traffic and waits for an acquire to initiate

	modeline='#type='
	leftsubnetline='#leftsubnet='
	rightsubnetline='#rightsubnet='
	triggers=

	case ${mode} in
	    transport )
		west=${west_internet4}
		west_westnet=${west_westnet4}
		east=${east_internet4}
		rise=${rise_eastnet4}
		set=${set_westnet4}
		modeline="type=transport"
		what="host-to-host transport mode"
		conn=west-east
		hosts=${platform}east-${platform}west
		;;
	    transport-ondemand )
		west=${west_internet4}
		west_westnet=${west_westnet4}
		east=${east_internet4}
		rise=${rise_eastnet4}
		set=${set_westnet4}
		modeline="type=transport"
		what="ondemand host-to-host transport mode"
		conn=west-east
		hosts=${platform}east-${platform}west
		triggers="west-udp7-east" # west-ping-east west-iping-east"
		;;
	    tunnel )
		west=${west_internet6}
		west_westnet=${west_westnet6}
		east=${east_internet6}
		rise=${rise_eastnet6}
		set=${set_westnet6}
		what="IPv6 host-to-host tunnel mode"
		conn=west-east
		hosts=${platform}east-${platform}west
		;;
	    tunnel-forward )
		west=${west_internet4}
		west_westnet=${west_westnet4}
		east=${east_internet4}
		rise=${rise_eastnet4}
		set=${set_westnet4}
		leftsubnetline="leftsubnet=${westnet4}0/24"
		rightsubnetline="rightsubnet=${eastnet4}0/24"
		what="rise-east=TUNNEL=west-set"
		conn=westnet-eastnet
		hosts=${platform}east-${platform}rise-${platform}set-${platform}west
		;;
	    tunnel-ondemand )
		west=${west_internet4}
		west_westnet=${west_westnet4}
		east=${east_internet4}
		rise=${rise_eastnet4}
		set=${set_westnet4}
		leftsubnetline="leftsubnet=${westnet4}0/24"
		rightsubnetline="rightsubnet=${eastnet4}0/24"
		what="rise-east=TUNNEL=west-set triggered by an acquire"
		conn=westnet-eastnet
		# only Linux's SOCAT/NC allow dest port 0
		hosts=${platform}east-linuxrise-linuxset-${platform}west
		triggers="set-udp7-rise" # set-ping-rise west-udp7-east west-iping-east west-ping-east"
		;;
	esac

	# linux disables IPv6 unless swan-prep is told not to

	case ${platform}-${mode} in
	    linux-tunnel ) prep="/testing/guestbin/swan-prep --46" ;;
	    linux-* )      prep="/testing/guestbin/swan-prep" ;;
	    * )            prep="../../guestbin/prep.sh" ;;
	esac

	cat <<EOF > ${dir}/description.txt
${stack} ${what} on $(echo ${platform} | sed -e 's/linux/Linux/' -e 's/freebsd/FreeBSD/' -e 's/netbsd/NetBSD/' -e 's/openbsd/OpenBSD/')
EOF
	do_not_modify >> ${dir}/description.txt

	cat <<EOF > ${dir}/ipsec.conf
config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	plutodebug=all
	dumpdir=/tmp

conn ${conn}
	left=${west}
	leftid="@west"
	right=${east}
	rightid="@east"
	authby=secret
	${modeline}
	${leftsubnetline}
	${rightsubnetline}
	compress=no
	phase2=esp
EOF

	cat <<EOF > ${dir}/ipsec.secrets
@west @east : PSK "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
EOF

	# XXX: currently rise->set pings don't flow on freebsd in
	# transport mode.

	case ${mode} in
	    tunnel-* )
		touch ${dir}/east.console.txt
		touch ${dir}/west.console.txt
		touch ${dir}/rise.console.txt
		touch ${dir}/set.console.txt
		;;
	    * )
		touch ${dir}/east.console.txt
		touch ${dir}/west.console.txt
		;;
	esac

	rm -f ${dir}/all.*.sh
	sh=${dir}/all.${hosts}.sh
	do_not_modify > ${sh}

	echo >> ${sh}
	cat <<EOF >> ${sh}
east# ${prep}
east# ipsec start
east# ../../guestbin/wait-until-pluto-started
east# ipsec add ${conn}
east# echo "initdone"
EOF
	echo >> ${sh}
	cat <<EOF >> ${sh}
west# ${prep}
west# ipsec start
west# ../../guestbin/wait-until-pluto-started
west# ipsec add ${conn}
west# echo "initdone"
EOF


	case ${mode} in
	    *-ondemand )
		    echo >> ${sh}
		    cat <<EOF >> ${sh}
west# ipsec route ${conn}
west# ipsec _kernel state
west# ipsec _kernel policy
EOF
		for trigger in ${triggers} ; do
		    ondemand ${trigger} >> ${sh}
		    ping_hosts ${mode} >> ${sh}
		    cat <<EOF >> ${sh}
# wait for larval state to clear; hack
west# ../../guestbin/wait-for.sh --no-match 'spi 0x00000000' ipsec _kernel state
west# ipsec _kernel state
west# ipsec _kernel policy
EOF
		    down >> ${sh}
		    #delete >> ${sh}
		    #stop >> ${sh}
		done
		;;
	    * )
		up >> ${sh}
		ping_hosts ${mode} >> ${sh}
		down >> ${sh}
		;;
	esac

    done
done
