#!/bin/sh
#
# Called my "make check"
# It was not put inside the python helper because it caused display
# problems and delays

POOL=$1
OSTYPE=$2
OSMEDIA=$3

# check for hardware VM instructions
cpu="--hvm"
grep vmx /proc/cpuinfo > /dev/null || cpu=""

# install base guest to obtain a file image that will be used as uml root
# For static networking add kernel args parameters ip=.... etc
# (network settings in kickstart are ignored by modern dracut)
virt-install --connect=qemu:///system \
  --network=network:default,model=virtio \
  --initrd-inject=testing/libvirt/"$OSTYPE"base.ks \
  --extra-args='swanname=swan"$OSTYPE"base ks=file:/"$OSTYPE"base.ks \
  console=tty0 console=ttyS0,115200' \
  --name=swan"$OSTYPE"base \
  --disk $POOL/swan"$OSTYPE"base.img,size=8 \
  --ram 1024 \
  --vcpus=1 \
  --check-cpu \
  --accelerate \
  --location=$OSMEDIA \
  --nographics \
  --autostart \
  --noreboot \
  $cpu

