connections {
	westnet-eastnet-ikev2a {
		#=Right
		fragmentation=yes
		version=2
		local_addrs=192.1.2.23
		remote_addrs=192.1.2.45
		proposals=3des-md5-modp2048
		children {
			westnet-eastnet-ikev2a {
				start_action=none
				esp_proposals=aes128-sha2_512
				remote_ts=192.0.1.0/24
				local_ts=192.0.2.0/24
			}
			
			westnet-eastnet-ikev2b {
				start_action=none
				esp_proposals=aes128-sha2_512
				remote_ts=192.0.100.0/24
				local_ts=192.0.200.0/24
			}
			
			westnet-eastnet-ikev2c {
				start_action=none
				esp_proposals=aes128-sha2_512
				remote_ts=192.0.101.0/24
				local_ts=192.0.201.0/24
			}
			
		}
		local-0 {
			auth = psk
			id = @east
		}
		remote-0 {
			auth = psk
			id = @west
		}
	}
}
pools {
}
authorities {
}
secrets {
	ike-@east@west {
		secret = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
		id-0=@east
		id-1=@west
	}
}
