#####
##### GENERATED BY testing/utils/host-to-host.sh
#####   do not modify

east# ../../guestbin/prep.sh
east# ipsec start
east# ../../guestbin/wait-until-pluto-started
east# ipsec whack --impair suppress_retransmits
east# ipsec add westnet-eastnet
east# echo "initdone"

west# ../../guestbin/prep.sh
west# ipsec start
west# ../../guestbin/wait-until-pluto-started
west# ipsec add westnet-eastnet
west# echo "initdone"

west# ipsec route westnet-eastnet
west# ipsec _kernel state
west# ipsec _kernel policy

# trigger acquire using UDP
set# echo 'TRIGGER' | nc -u -w 1 192.0.2.12 7
west# ../../guestbin/wait-for-pluto.sh '^".*#2: initiator established Child SA'
rise# ../../guestbin/ping-once.sh --up 192.0.1.15
set# ../../guestbin/ping-once.sh --up 192.0.2.12
east# ipsec whack --trafficstatus

# wait for larval state to clear; hack
east# ../../guestbin/wait-for.sh --no-match 'spi 0x00000000' ipsec _kernel state
east# ipsec _kernel state
east# ipsec _kernel policy
west# ipsec down westnet-eastnet
west# ipsec _kernel state
