config setup
	# put the logs in /tmp for the UMLs, so that we can operate
	# without syslogd, which seems to break on UMLs
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	dumpdir=/tmp
	plutodebug=all

conn rise-set
	authby=secret
        leftid=@west
        rightid=@east
        left=198.18.1.12
        right=198.18.1.15
        leftsubnet=0.0.0.0/0
        rightsubnet=0.0.0.0/0
	esp=aes-sha1
	ipsec-interface=yes
	right-updown=
