connections {
	psk {
		aggressive=yes
		proposals=aes-sha1-modp1536, default
		version=1
		local_addrs=192.1.2.45
		remote_addrs=192.1.2.23
		children {
			psk {
				start_action=none
				esp_proposals=aes-sha1-modp1536, default
			}
			
		}
		local-0 {
			auth = psk
			id = @vpnclient
		}
		remote-0 {
			auth = psk
			id = @vpnserver
		}
	}
}
pools {
}
authorities {
}
secrets {
	ike- {
		secret = "test"
	}
}
