connections {
	rw-eap {
		fragmentation=yes
		version=2
		local_addrs=192.1.2.23
		remote_addrs=%any
		#rightsend_cert=never
		children {
			rw-eap {
				start_action=none
				local_ts=192.0.2.0/24
				remote_ts=192.0.1.0/24
				#firewall=yes
			}
			
		}
		local-0 {
			auth = pubkey
			certs = /etc/strongswan/swanctl/x509/east.crt
			id = @east.testing.libreswan.org
		}
		remote-0 {
			auth = eap-md5
			id = *@testing.libreswan.org
		}
	}
}
pools {
}
authorities {
}
secrets {
	rsa- {
		file=/etc/strongswan/swanctl/rsa/east.key
	}
	eap-user1@testing-libreswan-org {
		secret = "p@ssw0rd"
		id-0=user1@testing.libreswan.org
	}
}
