connections {
	rw-eap {
		local_addrs=192.1.2.45
		remote_addrs=192.1.2.23
		children {
			rw-eap {
				start_action=none
				local_ts=192.0.1.0/24
				remote_ts=192.0.2.0/24
				#firewall=yes
			}
			
		}
		local-0 {
			auth = eap
			id = user1@testing.libreswan.org
		}
		remote-0 {
			auth = pubkey
			id = @east.testing.libreswan.org
		}
	}
}
pools {
}
authorities {
}
secrets {
	eap-user1@testing-libreswan-org {
		secret = "p@ssw0rd"
		id-0=user1@testing.libreswan.org
	}
}
