connections {
	westnet-eastnet-ikev1 {
		#=needs
		proposals=aes-sha1-modp2048
		version=1
		local_addrs=192.1.2.23
		remote_addrs=192.1.2.45
		pools=pool-subnet-192-0-1-254/32
		children {
			westnet-eastnet-ikev1 {
				start_action=none
				esp_proposals=aes-sha1-modp2048
				local_ts=0.0.0.0/0
				remote_ts=0.0.0.0/0
			}
		}
		local-0 {
			auth = psk
			id = @east
		}
		remote-0 {
			auth = psk
			id = @west
		}
		remote-1 {
			auth = xauth
		}
	}
}
pools {
	pool-subnet-192-0-1-254/32 {
		addrs=192.0.1.254/32
	}
}
authorities {
}
secrets {
	ike-@east@west {
		secret = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
		id-0=@east
		id-1=@west
	}
	eap-@use3 {
		secret = "use1pass"
		id-0="use3"
	}
}
