config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	plutodebug=all
	dumpdir=/tmp

conn rise-set
	left=2001:db8:1::12
	leftid="@rise"
	right=2001:db8:1::15
	rightid="@set"
	authby=secret
	compress=no
	phase2=esp
